### PR TITLE
Fix: Move build steps to appropriate sections

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] updates composer itself in the `before_install` section
* [x] installs dependencies in the `install` section
* [x] uploads coverage in the `after_success` section (as there's no need to upload coverage when the build failed)

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
:+1:

**Comment by sagikazarmark** [comment]
:+1:

**Comment by philsturgeon** [comment]
Needs rebase

**Comment by localheinz** [comment]
@philsturgeon 

Done!

**Comment by localheinz** [comment]
@philsturgeon 

Build failure is related to Scrutinizer choking on something.

**Comment by philipobenito** [comment]
Yes I've got that fixed locally, with all these pulled in, be pushing tomorrow



—

**Pull request merged**
