### PR TITLE
Added trait for ContainerAwareInterface

### PR DESCRIPTION
**Pull request by hannesvdvreken**
orno/di#38

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
@philipobenito rebased new commit with fixed docblock

**Comment by philipobenito** [comment]
Thanks :+1:

**Comment by mcallan83** [comment]
Are there any examples that show how to use this trait?

**Comment by hannesvdvreken** [comment]
Here's an example in the source code of the container itself:
https://github.com/thephpleague/container/blob/master/src/Definition/CallableDefinition.php

**Comment by mcallan83** [comment]
Thanks for the quick reply!  


--  
Mike Callan
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Pull request merged**
