### PR TITLE
Resetting shared items

### PR DESCRIPTION
**Pull request by hannesvdvreken**
This should solve the unexpected behaviour described in #111.

### CODE REVIEW

**Comment by philipobenito** [comment]
Cheers @hannesvdvreken will merge and tag when I get a spare minute this week.

**Comment by fterragna** [comment]
@philipobenito are you still planning on merging this soon?

**Comment by philipobenito** [comment]
Sorry, will have a look this weekend.

**Comment by fterragna** [comment]
OK. If you need help moving some of these PRs through, I'd be glad to help out!

**Pull request merged**
