### PR TITLE
Add ability to set arguments in shared definitions

### PR DESCRIPTION
**Pull request by valinurovam**
Hi all.
Is it possible to add ability to create shared definitions with arguments like this?

### CODE REVIEW

**Comment by valinurovam** [comment]
Hi all.
Any changes?

**Comment by nebulousGirl** [comment]
I would say that using arguments with shared instances is not supposed to work. The only reason to use a shared instance is when you want the same object to be used by other services, so you should not be able to change the instance with arguments.

In your case, you should be using the factory pattern which returns a new instance according to the arguments you pass in the ``get`` method.

**Comment by philipobenito** [comment]
@nebulousGirl is indeed correct here.

**Comment by 2nick** [comment]
Hi all.

Not sure I'm quite understand - if I want to have DataMapper which I want to be single instance with single instance of db-connection inside, how do you suggest to code it without shared instances? Create new DataMapper instance on each `get` call?

**Comment by nebulousGirl** [comment]
You can use `` share`` when you want only want instance, but you can't use arguments when calling ``get`` for a shared service.

```php
$container->add('service', 'SomeClass');
//This would work and effectively pass the argument to the class constructor 
$container->get('service', ['someArg']); 

$container->share('serviceShared', 'SomeClass');
//While this would not pass the argument to the constructor 
//because it is a shared service (single instance) and it doesn't get reinstanciated
$container->get('serviceShared', ['someArg']);

**Comment by philipobenito** [comment]
@2nick you'd just set the database connection as shared and pass that in to a data mapper at the time you define the objects in the container, you don't need to pass arguments when you retrieve the data mapper.

```php
$container
    ->share('Some\Database\Driver')
    ->withArgument(new RawArgument(['host', 'user', 'pass']))
;

$container
    ->share('Some\Data\Mapper')
    ->withArgument('Some\Database\Driver')
;

$container->get('Some\Data\Mapper');

```

**Pull request closed without merging**
