### PR TITLE
Fix: Remove unused imports

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] removes unused imports in test code

### CODE REVIEW

**Comment by philipobenito** [comment]
@localheinz A little fiddling is needed from me on your PRs as master is now dev branch for v2 with a lot of changes locally. If you have time would you be able to re submit them against the `1.x`. If you don't have time please let me know and I will do it manually and bring them across to `master` for v2.

Thanks for these by the way.

**Comment by localheinz** [comment]
@philipobenito 

No problem, give me a moment!

**Comment by localheinz** [comment]
@philipobenito 

Turns out that this has already been fixed in `develop`, closing!

**Comment by localheinz** [comment]
@philipobenito 

Not sure, shouldn't you make `develop` the default branch, then?

**Comment by philipobenito** [comment]
@localheinz 

Yeah I'm in the process of changing the dev strategy as I'm building v2. Should all be finalised quite soon, just been a mad few months, but will be sorting it asap.

**Comment by localheinz** [comment]
@philipobenito 

:+1: Take it easy!

**Comment by philipobenito** [comment]
@localheinz 

Idea is that `develop` will disappear completely, there are just too many changes going through that will break `master` completely so it's a bit of a stop gap :+1:

**Pull request closed without merging**
