### PR TITLE
PHP 8.4 compatibility

### PR DESCRIPTION
**Pull request by andypost**
RFC https://php.watch/rfcs/deprecate-implicitly-nullable-types

### CODE REVIEW

**Comment by andypost** [comment]
Testing via docker
```
$ docker run --rm -v $(pwd):/mnt -w /mnt php:8.4.0alpha2-cli-alpine find . -type f -name '*.php' -exec php -l {} \;
```

**Comment by ADmad** [comment]
You could update the matrix in https://github.com/thephpleague/container/blob/4.x/.github/workflows/test.yml to include PHP 8.4

**Comment by andypost** [comment]
I can't see if the workflow is running, so the second commit is not tested

**Comment by ADmad** [comment]
@philipobenito ping

**Comment by dereuromark** [comment]
Maybe under group `thephpleague` there is more than one author available with merge/commit rights?

**Comment by philipobenito** [comment]
Will merge next week, just finishing off some major version work.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by weitzman** [comment]
PHP 8.4 is now in release candidate phase. Would be good to merge this soon.

**Comment by LordSimal** [comment]
Friendly reminder to @philipobenito to get this merged and released, so that everyone can easily test their packages before 8.4 gets out

**Comment by ADmad** [comment]
Hi @philipobenito, if you are unable to devote time towards the maintenance of this package kindly give access to someone else who can help you or invite maintainers.

**Pull request merged**
