### PR TITLE
Update dependencies for PSR-11

### PR DESCRIPTION
**Pull request by hannesvdvreken**
### Changed

- Increase minimum version of container-interop in order to implement PSR-11 interface.

---
see #122

### CODE REVIEW

**Comment by philipobenito** [comment]
Yeah open to this, does it require an interface change then or is it handled by the container-interop increment?

**Comment by hannesvdvreken** [comment]
See https://github.com/container-interop/container-interop/releases/tag/1.2.0

**Comment by philipobenito** [comment]
👍  might be tomorrow before I can tag

**Comment by hannesvdvreken** [comment]
All good, man!

**Pull request merged**
