### PR TITLE
Enhancement: Allow installation with psr/container:^2.0.0

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

* [x] allows installation with `psr/container:^2.0.0`

### CODE REVIEW

**Comment by philipobenito** [comment]
Will merge and tag this tomorrow morning

**Comment by localheinz** [comment]
Thank you, @philipobenito!

**Comment by philipobenito** [comment]
I just need to figure out the action failures before a tag

**Comment by philipobenito** [comment]
I've backported to 3.x too @localheinz so it's in 3.3.5 and dev-4.x

**Pull request merged**
