### PR TITLE
Provider signature bc

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Alternative implementation of #93 that preserves backwards compatibility.

### CODE REVIEW

**Comment by philipobenito** [comment]
I think #93 is obviously a better solution but at this time I would prefer to preserve BC so I think this will be the way to go. I do think we require the interface to be a setter and getter though then it allows for setting of the signature both via construction, but also that the functionality is provided by default.

I think based on naming structures throughout the project we should go with `ServiceProviderSignatureInterface::withSignature` and `ServiceProviderSignatureInterface::getSignature`, we should also provide an extra abstract to ensure return `self`, this means we can register a service provider as below.

```php
<?php

$container->addServiceProvider((new WhateverServiceProvider)->withSignature('blah.blah'));
```

Due to timezone differences, I'll put these changes in to `2.x-dev`/`dev-master` then you have something to work with and then if you're happy, let me know and I'll tag it.

**Comment by greg-1-anderson** [comment]
Perfect!  Thanks so much for cleaning it up.

**Comment by philipobenito** [comment]
https://github.com/thephpleague/container/releases/tag/2.2.0 :+1:

**Comment by philipobenito** [comment]
Thanks again for your input @greg-1-anderson

**Pull request merged**
